### PR TITLE
feat: Backport minimum commission to v0.45.0

### PR DESCRIPTION
**Pull request by lydia-pierce**
backport the minimum commission from [#10529](https://github.com/cosmos/cosmos-sdk/pull/10529) into v0.45.0

### CODE REVIEW

**Comment by evan-forbes** [comment]
Do you happen to know what the liveness test is failing? I don't think this was failing in the previous version, but github deleted the results of that PR's CI run. However, I feel like I've ran into this issue before, but forgot what we did to fix it. If its something silly then we can ignore it, but we should obvi be careful since we did introduce changes that might not be compatible

Not sure if we should bother fixing the linter tho, I'll leave it up to you 
```
No release type found in pull request title "Backport minimum commission to v0.45.0". Add a prefix to indicate what kind of release this pull request corresponds to (see https://www.conventionalcommits.org/).
```

**Comment by evan-forbes** [comment]
ahh I see
```
Step 5/18 : COPY db/go.mod db/go.sum /work/db/
COPY failed: file not found in build context or excluded by .dockerignore: stat db/go.mod: file does not exist
```

yeah, we can _probably_ ignore that, but we should definitely be very careful, and still test using this branch in a live chain before we can be certain

**Review by evan-forbes — APPROVED** [review]
:shipit: 

we should perform further testing to make sure, and would prefer if the linter wasn't failing, but pre-approvingggggg

**Comment by lydia-pierce** [comment]
I just had to add the "feat" prefix to the name of the PR to fix one of the errors.

Two of the failed checks "Tests/Code Coverage/test-rosetta" and "Tests/Code Coverage/liveness-test" also failed in the [original PR for this feature](https://github.com/cosmos/cosmos-sdk/actions/runs/1452896245), so it doesn't seem like a big concern.

The last failed check "Protobuf/breakage" only passed in [the original PR](https://github.com/cosmos/cosmos-sdk/runs/4189248478?check_suite_focus=true) because there were no logs available, so I'm not sure if that one's actually a problem for us or not.

I'll test the code on my own and find out.

**Comment by evan-forbes** [comment]
> Two of the failed checks "Tests/Code Coverage/test-rosetta" and "Tests/Code Coverage/liveness-test" also failed in the [original PR for this feature](https://github.com/cosmos/cosmos-sdk/actions/runs/1452896245), so it doesn't seem like a big concern.

just for clarity for any future readers, like suggested in https://github.com/pomifer/cosmos-sdk/pull/2#issuecomment-1055923816 this failure is probably ok because the CI not being designed for a github fork. This is also the reason why is fails in other cosmos-sdk forks and before. Thanks for testing to make sure tho!!

>The last failed check "Protobuf/breakage" only passed in [the original PR](https://github.com/cosmos/cosmos-sdk/runs/4189248478?check_suite_focus=true) because there were no logs available, so I'm not sure if that one's actually a problem for us or not.

We changed the proto files, so this is expected. The entire point of the test is to make sure that reviewers do not miss this.

**Pull request merged**
